2024-04-22T02:08:53.188857+00:00 CRITICAL 'ansible_navigator.actions.run_2826._handle_message' Unhandled message from runner queue, discarded: {'event': 'verbose', 'uuid': 'e5173f2b-b7d4-4670-87ce-a2744b2473e3', 'counter': 1, 'stdout': '\x1b[0;31mERROR! the playbook: file.yml could not be found\x1b[0m', 'start_line': 0, 'end_line': 1, 'runner_ident': '48a7f979-157a-4579-8c9d-9e9dcd95ad59', 'created': '2024-04-22T02:08:53.188574'}
2024-04-22T02:08:53.393740+00:00 ERROR 'ansible_navigator.actions.run_2826.write_artifact' Saving the artifact file failed, resulted in the following error: f[Errno 13] Permission denied: '/file-artifact-2024-04-22T02:08:53.393092+00:00.json'
2024-04-22T02:09:00.851626+00:00 CRITICAL 'ansible_navigator.actions.run_20a1._handle_message' Unhandled message from runner queue, discarded: {'event': 'verbose', 'uuid': '96892b9c-1a1b-4e13-914f-47b0c44e97dd', 'counter': 1, 'stdout': '\x1b[0;31mERROR! the playbook: file.yml could not be found\x1b[0m', 'start_line': 0, 'end_line': 1, 'runner_ident': '20fe86be-2d82-4c4a-8cb8-8638107fa696', 'created': '2024-04-22T02:09:00.851309'}
2024-04-22T02:09:01.057702+00:00 ERROR 'ansible_navigator.actions.run_20a1.write_artifact' Saving the artifact file failed, resulted in the following error: f[Errno 13] Permission denied: '/file-artifact-2024-04-22T02:09:01.056233+00:00.json'
